config/routes.rb
Todo::Application.routes.draw do
  

  root :to => "static#home"

  match "tasks/sort" => "tasks#sort"
  match "tasks/update_completed" => "tasks#update_completed"
  match "tasks/get_tasks_completed_on_date" => "tasks#get_tasks_completed_on_date"
  match "tasks/get_current_tasks" => "tasks#get_current_tasks"
  match "/all" => "tasks#all"
  
  resources :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :prepare_for_mobile

  private

  def mobile_device?
  	# request.format = :mobile if request.user_agent =~ /iPhone/
	  if session[:mobile_param]
	    session[:mobile_param] == "1"
	  else
	    request.user_agent =~ /Mobile|webOS/
	  end  	
  end

  helper_method :mobile_device?

  def prepare_for_mobile
  	session[:mobile_param] = params[:mobile] if params[:mobile]
  	request.format = :mobile if mobile_device?
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
    @tasks = Task.where("completed_at > ? or completed_at is null", Date.today.beginning_of_day).order(:position)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def all
    render :json => Task.all
  end

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all(:order => "position")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])
    @task.position = params[:position]
    render :json => @task.id if @task.save   

    # respond_to do |format|
    #   if @task.save
    #     format.html { redirect_to @task, notice: 'Task was successfully created.' }
    #     format.json { render json: @task, status: :created, location: @task }
    #   else
    #     format.html { render action: "new" }
    #     format.json { render json: @task.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    render :nothing => true

    # respond_to do |format|
    #   format.html { redirect_to tasks_url }
    #   format.json { head :ok }
    # end
  end

  def sort
    params["task_list"].each_with_index do |task, i|
      Task.find(task.split("_")[1]).update_attribute "position", i + 1
    end
    render :nothing => true
  end

  def update_completed
    if params[:completed] == "true" 
      Task.find(params[:task_id]).update_attribute "completed_at", Time.now 
    else 
      Task.find(params[:task_id]).update_attribute "completed_at", nil
    end
    render :nothing => true
  end

  def get_tasks_completed_on_date
    date = Date.parse(params[:date]).to_date
    @tasks = Task.where("completed_at > ? and completed_at < ?", date.beginning_of_day, date.end_of_day)
    render :partial => "list"
  end

  def get_current_tasks    
    render :json => Task.where("completed_at > ? or completed_at is null", Date.today.beginning_of_day).order(:position)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    "application" %>
  <%= stylesheet_link_tag    "mobile" if mobile_device? %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_list.html.haml
- @tasks.each do |task|  
  %li{:id => "task_#{task.id}", :class => "task", :task_id => task.id}
    - if task.completed_at
      = check_box task, :completed, :class => "task_checkbox", :checked => "checked"
      = best_in_place task, :name, :type => :input, :task_id => task.id, :style => "text-decoration: line-through;", :inner_class => "task_input"
    -else 
      = check_box task, :completed, :class => "task_checkbox"
      = best_in_place task, :name, :type => :input, :task_id => task.id, :inner_class => "task_input"
    = label nil, "X", :class => "delete_label", :task_id => task.id

app/views/tasks/_task.html.haml
%li{:id => "@task_#{@task.id}", :class => "@task", :@task_id => @task.id}
  - if @task.completed_at
    = check_box @task, :completed, :class => "@task_checkbox", :checked => "checked"
    = best_in_place @task, :name, :type => :input, :@task_id => @task.id, :style => "text-decoration: line-through;", :inner_class => "@task_input"
  -else 
    = check_box @task, :completed, :class => "@task_checkbox"
    = best_in_place @task, :name, :type => :input, :@task_id => @task.id, :inner_class => "@task_input"
  = label nil, "X", :class => "delete_label", :@task_id => @task.id

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.haml
/ move home here 

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>User:</b>
  <%= @task.user_id %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>